// src/components/Lightbox.tsx
import React, { useEffect, useState, useRef } from 'react';
import { GifItem } from '../types';
import './Lightbox.css';

interface LightboxProps {
  gif: GifItem | null;
  isOpen: boolean;
  onClose: () => void;
  onNext?: () => void;
  onPrevious?: () => void;
}

const Lightbox: React.FC<LightboxProps> = ({ gif, isOpen, onClose, onNext, onPrevious }) => {
  const [isZoomed, setIsZoomed] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [imagePosition, setImagePosition] = useState({ x: 0, y: 0 });
  const containerRef = useRef<HTMLDivElement>(null);
  const imageRef = useRef<HTMLImageElement>(null);
  const dragStartRef = useRef({ x: 0, y: 0 });
  const imagePositionRef = useRef({ x: 0, y: 0 });
  
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;
      
      switch (e.key) {
        case 'Escape':
          if (isZoomed) {
            setIsZoomed(false);
          } else {
            onClose();
          }
          break;
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      document.body.style.overflow = '';
    };
  }, [isOpen, isZoomed, onClose, onNext, onPrevious]);

  // Reset zoom when gif changes
  useEffect(() => {
    setIsZoomed(false);
    setImagePosition({ x: 0, y: 0 });
    imagePositionRef.current = { x: 0, y: 0 };
  }, [gif]);

  // Handle mouse events for dragging
  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault();
    if (isZoomed) {
      setIsDragging(true);
      dragStartRef.current = {
        x: e.clientX - imagePositionRef.current.x,
        y: e.clientY - imagePositionRef.current.y
      };
    } else {
      setIsZoomed(true);
    }
  };

  useEffect(() => {
    const updateImageTransform = (x: number, y: number) => {
      if (imageRef.current) {
        imageRef.current.style.transform = `scale(2) translate(${x / 2}px, ${y / 2}px)`;
      }
    };

    const handleMouseMove = (e: MouseEvent) => {
      if (!isDragging || !isZoomed) return;
      
      const newX = e.clientX - dragStartRef.current.x;
      const newY = e.clientY - dragStartRef.current.y;
      
      imagePositionRef.current = { x: newX, y: newY };
      updateImageTransform(newX, newY);
    };

    const handleMouseUp = () => {
      setIsDragging(false);
      // Update React state once when dragging stops
      setImagePosition({ ...imagePositionRef.current });
    };

    if (isDragging) {
      document.addEventListener('mousemove', handleMouseMove, { passive: true });
      document.addEventListener('mouseup', handleMouseUp);
    }

    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging, isZoomed]);

  if (!isOpen || !gif) return null;

  return (
    <div 
      className="lightbox-overlay" 
      onClick={isZoomed ? () => { 
        setIsZoomed(false); 
        setImagePosition({ x: 0, y: 0 }); 
        imagePositionRef.current = { x: 0, y: 0 };
      } : onClose}
    >
      <div 
        ref={containerRef}
        className="lightbox-container" 
        onClick={(e) => e.stopPropagation()}
      >
        <div className="lightbox-content">
          <img 
            ref={imageRef}
            src={gif.path} 
            alt={gif.name}
            className={`lightbox-image ${isZoomed ? 'zoomed' : ''} ${isDragging ? 'dragging' : ''}`}
            onMouseDown={handleMouseDown}
            style={{ 
              cursor: isZoomed ? (isDragging ? 'grabbing' : 'grab') : 'zoom-in',
              transform: isZoomed ? `scale(2) translate(${imagePosition.x / 2}px, ${imagePosition.y / 2}px)` : 'scale(1)',
              willChange: isDragging ? 'transform' : 'auto'
            }}
          />
        </div>
      </div>
    </div>
  );
};

export default Lightbox;

// src/lib/Lightbox.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { GifItem } from '../types';

  export let gif: GifItem | null;
  export let isOpen: boolean;
  export let onClose: () => void;
  export let onNext: (() => void) | undefined = undefined;
  export let onPrevious: (() => void) | undefined = undefined;

  let isZoomed = false;
  let isDragging = false;
  let imagePosition = { x: 0, y: 0 };
  let imageRef: HTMLImageElement | null = null;
  let dragStart = { x: 0, y: 0 };
  let imagePositionRef = { x: 0, y: 0 };

  // Reset zoom when gif changes
  $: if (gif) {
    isZoomed = false;
    imagePosition = { x: 0, y: 0 };
    imagePositionRef = { x: 0, y: 0 };
  }

  // Handle body overflow
  $: if (isOpen) {
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = '';
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (!isOpen) return;

    if (e.key === 'Escape') {
      if (isZoomed) {
        isZoomed = false;
      } else {
        onClose();
      }
    }
  }

  function handleMouseDown(e: MouseEvent) {
    e.preventDefault();
    if (isZoomed) {
      isDragging = true;
      dragStart = {
        x: e.clientX - imagePositionRef.x,
        y: e.clientY - imagePositionRef.y
      };
    } else {
      isZoomed = true;
    }
  }

  function handleMouseMove(e: MouseEvent) {
    if (!isDragging || !isZoomed) return;

    const newX = e.clientX - dragStart.x;
    const newY = e.clientY - dragStart.y;

    imagePositionRef = { x: newX, y: newY };
    if (imageRef) {
      imageRef.style.transform = `scale(2) translate(${newX / 2}px, ${newY / 2}px)`;
    }
  }

  function handleMouseUp() {
    isDragging = false;
    imagePosition = { ...imagePositionRef };
  }

  function handleOverlayClick() {
    if (isZoomed) {
      isZoomed = false;
      imagePosition = { x: 0, y: 0 };
      imagePositionRef = { x: 0, y: 0 };
    } else {
      onClose();
    }
  }

  function handleContainerClick(e: MouseEvent) {
    e.stopPropagation();
  }

  onMount(() => {
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousemove', handleMouseMove);
    document.addEventListener('mouseup', handleMouseUp);
  });

  onDestroy(() => {
    document.removeEventListener('keydown', handleKeyDown);
    document.removeEventListener('mousemove', handleMouseMove);
    document.removeEventListener('mouseup', handleMouseUp);
    document.body.style.overflow = '';
  });
</script>

{#if isOpen && gif}
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-static-element-interactions -->
  <div class="lightbox-overlay" on:click={handleOverlayClick}>
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-static-element-interactions -->
    <div class="lightbox-container" on:click={handleContainerClick}>
      <div class="lightbox-content">
        <!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
        <img
          bind:this={imageRef}
          src={gif.path}
          alt={gif.name}
          class="lightbox-image"
          class:zoomed={isZoomed}
          class:dragging={isDragging}
          on:mousedown={handleMouseDown}
          style="cursor: {isZoomed ? (isDragging ? 'grabbing' : 'grab') : 'zoom-in'};
                 transform: {isZoomed ? `scale(2) translate(${imagePosition.x / 2}px, ${imagePosition.y / 2}px)` : 'scale(1)'};
                 will-change: {isDragging ? 'transform' : 'auto'};"
        />
      </div>
    </div>
  </div>
{/if}

<style>
  .lightbox-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(10, 22, 40, 0.95);
    backdrop-filter: blur(10px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 2000;
    animation: fadeIn 0.3s ease-out;
  }

  .lightbox-container {
    position: relative;
    max-width: 95vw;
    max-height: 95vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    overflow: auto;
  }

  .lightbox-content {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .lightbox-image {
    max-width: 98vw;
    max-height: 95vh;
    width: auto;
    height: auto;
    object-fit: contain;
    border-radius: 0;
    animation: scaleIn 0.3s ease-out;
    transition: cursor 0.2s ease;
    cursor: zoom-in;
  }

  .lightbox-image.zoomed {
    max-width: none;
    max-height: none;
  }

  .lightbox-image.dragging {
    user-select: none;
    transition: none;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  @keyframes scaleIn {
    from {
      opacity: 0;
      transform: scale(0.8);
    }
    to {
      opacity: 1;
      transform: scale(1);
    }
  }

  @media (max-width: 768px) {
    .lightbox-image {
      max-width: 95vw;
      max-height: 90vh;
    }
  }
</style>
